import type { Metadata } from "next";

export const SITE = {
  name: "Ramest Technolabs",
  legalName: "Ramest Technolabs",
  url: "https://www.ramesttechnolabs.com",
  email: "hr@ramesttechnolabs.com",
  phone: "+919510903725",
  phoneDisplay: "+91 9510903725",
  address: {
    street: "RE11 - 2nd Floor, Iscon, Ambli Rd",
    city: "Ahmedabad",
    region: "Gujarat",
    postalCode: "380058",
    country: "IN",
  },
  /** Approximate coordinates for the Iscon / Ambli Road area, Ahmedabad. */
  geo: { latitude: 23.0225, longitude: 72.5074 },
  description:
    "Ramest Technolabs - Leading IT company providing Web Development, App Development, UI/UX Design, and AI/ML Solutions to transform your business.",
  logo: "/assets/logo_final.png",
  /** 1200x630 social share card generated by app/opengraph-image.tsx. */
  ogImage: "/opengraph-image",
  /**
   * Real photograph of the company — team or office, landscape, ideally
   * 1200x630 or larger.
   *
   * ⚠️ EMPTY = Google has no company photo to attach to this entity, so it
   * picks a loosely-related image from elsewhere on the web (this is exactly
   * why a competitor's office photo has been appearing next to our result).
   * Drop a real photo at /assets/team-photo.jpg and set the path here.
   */
  teamPhoto: "",
  locale: "en_IN",
  foundingYear: "2019",
  openingHours: "Mo-Sa 09:30-19:00",
} as const;

/**
 * Public profiles, used for both the footer icons and Organization.sameAs —
 * the strongest Knowledge Graph association signal.
 *
 * ⚠️ ADD REAL URLS HERE. Everything downstream is wired up and will light up
 * the moment entries are added: the footer renders icons only for profiles
 * listed here, and sameAs is derived from the same list. Only add URLs that
 * resolve — a broken sameAs is worse than an absent one.
 *
 * Example:
 *   { label: "LinkedIn", icon: "fa-brands fa-linkedin-in",
 *     href: "https://www.linkedin.com/company/ramest-technolabs/" },
 */
export const SOCIAL_LINKS: { label: string; icon: string; href: string }[] = [];

/** sameAs values for Organization schema — derived so the two never drift. */
export const SOCIAL_PROFILES: string[] = SOCIAL_LINKS.map((s) => s.href);

/** Stable @id values so schema nodes reference one another instead of repeating. */
export const ENTITY = {
  organization: `${SITE.url}/#organization`,
  website: `${SITE.url}/#website`,
  founder: `${SITE.url}/team#dax-panara`,
} as const;

export const FOUNDER = {
  name: "Dax Panara",
  role: "Founder & CEO",
  image: "/assets/dax-panara.webp",
} as const;

type PageMetaInput = {
  title: string;
  description: string;
  path?: string;
  image?: string;
  /** When true, use title as-is (no template suffix). Default false. */
  absoluteTitle?: boolean;
  /** Keep the page out of the index (404s, utility routes). */
  noindex?: boolean;
};

/** Consistent Metadata for every page — titles, OG, Twitter, canonical. */
export function createPageMetadata({
  title,
  description,
  path = "/",
  image = SITE.ogImage,
  absoluteTitle = false,
  noindex = false,
}: PageMetaInput): Metadata {
  const url = path === "/" ? SITE.url : `${SITE.url}${path}`;
  const ogTitle = absoluteTitle ? title : `${title} | ${SITE.name}`;

  return {
    title: absoluteTitle ? { absolute: title } : title,
    description,
    alternates: { canonical: url },
    openGraph: {
      type: "website",
      locale: SITE.locale,
      url,
      siteName: SITE.name,
      title: ogTitle,
      description,
      images: [{ url: image, width: 1200, height: 630, alt: ogTitle }],
    },
    twitter: {
      card: "summary_large_image",
      title: ogTitle,
      description,
      images: [image],
    },
    robots: noindex
      ? { index: false, follow: false, googleBot: { index: false, follow: false } }
      : { index: true, follow: true, googleBot: { index: true, follow: true } },
  };
}

const postalAddress = {
  "@type": "PostalAddress",
  streetAddress: SITE.address.street,
  addressLocality: SITE.address.city,
  addressRegion: SITE.address.region,
  postalCode: SITE.address.postalCode,
  addressCountry: SITE.address.country,
} as const;

/**
 * Candidate images for the Organization entity, best first. Google picks what
 * it shows in AI Overviews and knowledge panels from these; a logo alone is a
 * weak signal because it is not a photograph of the company.
 */
function organizationImages() {
  const images = [
    // Real photo first — the only candidate Google treats as a company image.
    ...(SITE.teamPhoto ? [`${SITE.url}${SITE.teamPhoto}`] : []),
    `${SITE.url}${SITE.ogImage}`,
    `${SITE.url}${SITE.logo}`,
  ];
  return images;
}

/** The founder as a first-class Person entity, linked to the company. */
export function founderJsonLd() {
  return {
    "@type": "Person",
    "@id": ENTITY.founder,
    name: FOUNDER.name,
    jobTitle: FOUNDER.role,
    image: `${SITE.url}${FOUNDER.image}`,
    worksFor: { "@id": ENTITY.organization },
    url: `${SITE.url}/team`,
  };
}

export function organizationJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    "@id": ENTITY.organization,
    name: SITE.name,
    legalName: SITE.legalName,
    alternateName: "Ramest",
    url: SITE.url,
    logo: {
      "@type": "ImageObject",
      url: `${SITE.url}${SITE.logo}`,
      caption: SITE.name,
      width: 687,
      height: 267,
    },
    image: organizationImages(),
    description: SITE.description,
    email: SITE.email,
    telephone: SITE.phoneDisplay,
    foundingDate: SITE.foundingYear,
    founder: founderJsonLd(),
    address: postalAddress,
    areaServed: [
      { "@type": "Country", name: "India" },
      { "@type": "Place", name: "Worldwide" },
    ],
    knowsAbout: [
      "Custom Software Development",
      "Web Application Development",
      "Mobile App Development",
      "Artificial Intelligence",
      "Large Language Models",
      "Cloud Infrastructure",
      "Data Engineering",
      "UI/UX Design",
    ],
    sameAs: SOCIAL_PROFILES,
    contactPoint: {
      "@type": "ContactPoint",
      telephone: SITE.phoneDisplay,
      contactType: "customer service",
      email: SITE.email,
      areaServed: "Worldwide",
      availableLanguage: ["English", "Hindi", "Gujarati"],
    },
  };
}

/** WebSite node — establishes the site entity and its publisher. */
export function websiteJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "WebSite",
    "@id": ENTITY.website,
    url: SITE.url,
    name: SITE.name,
    description: SITE.description,
    inLanguage: "en-IN",
    publisher: { "@id": ENTITY.organization },
  };
}

/**
 * LocalBusiness for the Ahmedabad office. Rendered only on /contact so Google
 * sees exactly one location node with the NAP it can cross-check against the
 * Google Business Profile.
 */
export function localBusinessJsonLd() {
  return {
    "@context": "https://schema.org",
    "@type": "ProfessionalService",
    "@id": `${SITE.url}/contact#localbusiness`,
    name: SITE.name,
    image: `${SITE.url}${SITE.logo}`,
    url: `${SITE.url}/contact`,
    telephone: SITE.phoneDisplay,
    email: SITE.email,
    address: postalAddress,
    geo: {
      "@type": "GeoCoordinates",
      latitude: SITE.geo.latitude,
      longitude: SITE.geo.longitude,
    },
    openingHours: SITE.openingHours,
    priceRange: "$$",
    parentOrganization: { "@id": ENTITY.organization },
    areaServed: [
      { "@type": "City", name: "Ahmedabad" },
      { "@type": "State", name: "Gujarat" },
      { "@type": "Country", name: "India" },
    ],
  };
}

export type Crumb = { name: string; path: string };

/** BreadcrumbList for nested routes — drives the breadcrumb SERP treatment. */
export function breadcrumbJsonLd(crumbs: Crumb[]) {
  return {
    "@context": "https://schema.org",
    "@type": "BreadcrumbList",
    itemListElement: crumbs.map((crumb, index) => ({
      "@type": "ListItem",
      position: index + 1,
      name: crumb.name,
      item: crumb.path === "/" ? SITE.url : `${SITE.url}${crumb.path}`,
    })),
  };
}
